services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: local

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      REACT_APP_API_TARGET: http://backend:8080
      VITE_USE_POLLING: 'true'
    volumes:
      - ${FRONTEND_PATH:-./frontend}:/app
      - /app/node_modules
    depends_on:
      - backend
